INSERT INTO `t_user` (`USR_ID`,`CREATED_AT`,`UPDATED_AT`,`USR_ACCOUNT_NON_EXPIRED`,`USR_ACCOUNT_NOT_LOCKED`,`USR_CREDENTIALS_NON_EXPIRED`,`USR_EMAIL`,`USR_ENABLED`,`USR_FIRST_NAME`,`USR_LAST_NAME`,`USR_PASSWORD`,`USR_USERNAME`) VALUES (1,'2020-04-30 00:12:56','2020-04-30 00:12:56',b'1',b'1',b'1','admin@admin.com',b'1',NULL,NULL,'$2a$10$bivNNnwn0voR4D7NM27ODuXHKdptzBk0fQhWOenhTq4Kmb9tZ5d.2','admin');
INSERT INTO `t_role` (`ROL_ID`, `ROL_NAME`) VALUES (1, 'ROLE_USER'), (2, 'ROLE_MODERATOR'), (3, 'ROLE_ADMIN');
INSERT INTO `t_authority` (`AUT_ID`, `AUT_NAME`) VALUES (1, 'ADD_CATEGORY'), (2, 'ADD_PLACE'), (3, 'UPDATE_USER_ROLE');
INSERT INTO `jt_user_role` (`USR_ID`, `ROL_ID`) VALUES (1, 1), (1, 2), (1, 3);
INSERT INTO `jt_role_authority` (`ROL_ID`, `AUT_ID`) VALUES (1, 2), (2, 1), (3, 3);
